djcode/djcode61_/gs/gs2/gs2/urls.py
from django.contrib import admin
from django.urls import path
from enroll import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.user_login, name='login'),
    path('dashboard/', views.user_dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
    path('index/', views.index, name='index'),
]

djcode/djcode61_/gs/gs2/enroll/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100)
    desc= models.CharField(max_length=200)

djcode/djcode61_/gs/gs2/enroll/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

# cleare your forms here.

class SignUpform(UserCreationForm):
    password2 = forms.CharField(label='confirm password (again)', widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {
            'email': 'Email'
        }

class EditUserProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'date_joined', 'last_login',]
        labels = {
            'email': 'Email'
        }

class EditAdminProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields = '__all__'
        labels = {
            'email': 'Email'
        }

djcode/djcode61_/gs/gs2/enroll/views.py
from email.headerregistry import Group
from django.shortcuts import render, HttpResponseRedirect
from enroll.forms import EditUserProfileForm
from enroll.forms import SignUpform, EditUserProfileForm, EditAdminProfileForm
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash



# Create your views here.

# this is Signup function.
def sign_up(request):
    if request.method == 'POST':
        form = SignUpform(request.POST)
        if form.is_valid():
            messages.success(request, 'SignedUp Successfully!!')
            user = form.save()
            group = Group.objects.get(name='Editor')
            user.groups.add(group)
    else:
        form = SignUpform()
    return render(request, 'enroll/signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            uname = form.cleaned_data['username']
            upwd = form.cleaned_data['password']
            user = authenticate(username=uname, password=upwd)
            login(request, user)
            messages.success(request, 'Logged In Successfully!!!')
        return HttpResponseRedirect('/dashboard/')
    else:
        form = AuthenticationForm()
    return render(request, 'enroll/login.html', {'form': form})

# User Dahsboard view function.
def user_dashboard(request):
    if request.user.is_anonymous:
        return HttpResponseRedirect('/login/')
        
    else:
        return render(request, 'enroll/dashboard.html', {'name': request.user.username})


# User logout view function.
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login/')

def index(request):
    if request.user.is_authenticated:
        print('Logged In')
    else:
        print('Not Logged In')
    return HttpResponseRedirect('/login/')

djcode/djcode61_/gs/gs2/enroll/templates/enroll/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <h1>Dashboard Page</h1>
    <h3>Welcome {{name}}</h3>
    {% if perms.enroll.delete_blog %}
    <input type="button" value="Delete"><br><br>
    {% else %}
    <h1>No Delete Permission</h1>
    {% endif %}

    {% if perms.enroll.add_blog %}
    <input type="button" value="Add"><br><br>
    {% else %}
    <h1>No Add Permission</h1>
    {% endif %}

    <a href="{% url 'index' %}">Index</a>
    <a href="{% url 'logout' %}">Logout</a>

</body>
</html>

djcode/djcode61_/gs/gs2/enroll/templates/enroll/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIn</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {% for fm in form %}
        {{fm.label_tag}}{{fm}}{{fm.errors}} <br><br>
        {% endfor %}
        <input type="submit" value="Login">
    </form>
    {% if mesaages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %} <br><br>
    <a href="{% url 'signup' %}">SignUp</a>
</body>
</html>

djcode/djcode61_/gs/gs2/enroll/templates/enroll/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUp</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {% for fm in form %}
        {{fm.label_tag}}{{fm}}{{fm.errors}} <br><br>
        {% endfor %}
        <input type="submit" value="SignUp">
    </form>
    {% if messages %}
    {% for message in messages %}
    {{message}}
    {% endfor %}
    {% endif %}
    <a href="{% url 'login' %}">Login</a><br><br>
</body>
</html>